openapi: 3.0.3
info:
  title: Bulk Import Service Contract
  description: Internal API contract for progressive bulk import operations
  version: 1.0.0

paths:
  /bulk-import/start:
    post:
      summary: Start bulk import operation
      description: |
        Initiates a new bulk import operation with the specified JQL query.
        Returns operation ID for progress tracking and control.
      operationId: startBulkImport
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jqlQuery
                - batchSize
              properties:
                jqlQuery:
                  type: string
                  description: JQL query to import tickets for
                  example: "project = MYPROJ AND status != Done"
                batchSize:
                  type: integer
                  description: Number of tickets per batch
                  minimum: 10
                  maximum: 100
                  default: 25
                maxResults:
                  type: integer
                  description: Maximum total tickets to import
                  minimum: 1
                  maximum: 1000
                  default: 1000
                allowDuplicates:
                  type: boolean
                  description: Whether to process tickets already in vault
                  default: false
                progressCallback:
                  type: boolean
                  description: Whether to provide progress callbacks
                  default: true
      responses:
        '200':
          description: Bulk import started successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  operationId:
                    type: string
                    format: uuid
                    description: Unique identifier for this operation
                    example: "550e8400-e29b-41d4-a716-446655440000"
                  estimatedCount:
                    type: integer
                    description: Estimated number of tickets to process
                    example: 150
                  estimatedDuration:
                    type: integer
                    description: Estimated duration in seconds
                    example: 180
                  batchCount:
                    type: integer
                    description: Number of batches to process
                    example: 6
        '400':
          description: Invalid request parameters
        '409':
          description: Another bulk import is already in progress

  /bulk-import/{operationId}/progress:
    get:
      summary: Get bulk import progress
      description: Returns current progress information for the specified operation
      operationId: getBulkImportProgress
      parameters:
        - name: operationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Progress information retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BulkImportProgress'
        '404':
          description: Operation not found

  /bulk-import/{operationId}/cancel:
    post:
      summary: Cancel bulk import operation
      description: |
        Requests cancellation of the bulk import operation.
        Current batch will complete before stopping.
      operationId: cancelBulkImport
      parameters:
        - name: operationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Cancellation requested
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Cancellation requested. Current batch will complete."
                  willStopAfterBatch:
                    type: integer
                    example: 3
        '404':
          description: Operation not found
        '409':
          description: Operation cannot be cancelled in current state

  /bulk-import/{operationId}/pause:
    post:
      summary: Pause bulk import operation
      description: |
        Pauses the bulk import operation after current batch completes.
        Operation can be resumed later.
      operationId: pauseBulkImport
      parameters:
        - name: operationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Operation paused
          content:
            application/json:
              schema:
                type: object
                properties:
                  resumeToken:
                    type: string
                    description: Token to resume the operation
                    example: "batch_3_token_abc123"
                  pausedAt:
                    type: string
                    format: date-time
                    example: "2025-09-10T14:30:00Z"

  /bulk-import/{operationId}/resume:
    post:
      summary: Resume paused bulk import operation
      description: Resumes a previously paused bulk import operation
      operationId: resumeBulkImport
      parameters:
        - name: operationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - resumeToken
              properties:
                resumeToken:
                  type: string
                  description: Token from pause operation
                  example: "batch_3_token_abc123"
      responses:
        '200':
          description: Operation resumed
        '400':
          description: Invalid resume token
        '404':
          description: Operation not found
        '409':
          description: Operation is not in paused state

components:
  schemas:
    BulkImportProgress:
      type: object
      properties:
        operationId:
          type: string
          format: uuid
          description: Unique operation identifier
        
        # Overall progress
        status:
          type: string
          enum: [
            "initializing",
            "searching", 
            "downloading",
            "processing",
            "paused",
            "cancelling", 
            "completed",
            "cancelled",
            "failed"
          ]
        
        # Progress metrics
        current:
          type: integer
          description: Current item being processed
          example: 73
        total:
          type: integer
          description: Total items to process
          example: 150
        processed:
          type: integer
          description: Successfully processed items
          example: 70
        failed:
          type: integer
          description: Failed items
          example: 2
        skipped:
          type: integer
          description: Skipped items (duplicates)
          example: 1
        
        # Batch information
        currentBatch:
          type: integer
          description: Current batch number (1-based)
          example: 3
        totalBatches:
          type: integer
          description: Total number of batches
          example: 6
        batchSize:
          type: integer
          description: Items per batch
          example: 25
        
        # Timing
        startTime:
          type: string
          format: date-time
          description: Operation start time
          example: "2025-09-10T14:00:00Z"
        lastUpdateTime:
          type: string
          format: date-time
          description: Last progress update time
          example: "2025-09-10T14:05:30Z"
        estimatedTimeRemaining:
          type: integer
          description: Estimated seconds remaining
          example: 45
        
        # Results
        newTicketsCreated:
          type: integer
          description: New tickets created in vault
          example: 65
        ticketsUpdated:
          type: integer
          description: Existing tickets updated
          example: 5
        duplicatesFound:
          type: integer
          description: Duplicate tickets skipped
          example: 1
        
        # Error tracking
        errors:
          type: array
          items:
            $ref: '#/components/schemas/BulkImportError'
        warnings:
          type: array
          items:
            type: string
          example: ["Ticket PROJ-456 has no summary"]
        
        # Control state
        cancellationRequested:
          type: boolean
          description: Whether cancellation has been requested
          default: false
        isPaused:
          type: boolean
          description: Whether operation is currently paused
          default: false
        resumeToken:
          type: string
          description: Token for resuming paused operation
          nullable: true

    BulkImportError:
      type: object
      properties:
        code:
          type: string
          enum: [
            "API_ERROR",
            "NETWORK_ERROR", 
            "VAULT_ERROR",
            "PARSE_ERROR",
            "RATE_LIMIT",
            "AUTH_ERROR"
          ]
        message:
          type: string
          description: Human-readable error message
          example: "Failed to create file for ticket PROJ-123"
        ticketId:
          type: string
          description: Jira ticket ID that caused the error
          example: "PROJ-123"
        batchNumber:
          type: integer
          description: Batch number where error occurred
          example: 2
        timestamp:
          type: string
          format: date-time
          example: "2025-09-10T14:03:45Z"
        retryable:
          type: boolean
          description: Whether this error can be retried
          default: true
        retryCount:
          type: integer
          description: Number of retry attempts made
          default: 0
        technicalDetails:
          type: object
          description: Technical error details for debugging
          properties:
            originalError:
              type: string
              description: Original error message
            stackTrace:
              type: string
              description: Stack trace (development only)
            apiResponse:
              type: object
              description: Jira API response that caused error